### ISSUE TITLE
in README node-roles link gives 404

### ISSUE THREAD

**Issue by kucharskim** [onflow/flow-validator#3]
README refers to https://developers.flow.com/next/building-on-flow/nodes/node-operation/node-roles but I get HTTP 404

**Comment by kucharskim** [comment]
I also get 404 with https://developers.flow.com/next/building-on-flow/nodes in the same readme

**Comment by kucharskim** [comment]
...actually all external links to https://developers.flow.com/ give 404

**Comment by vishalchangrani** [comment]
😞 sorry about that. I have fixed the links.

**Comment by kucharskim** [comment]
Cool. URLs work now. Thanks!
