### ISSUE TITLE
Firstset AG

### ISSUE THREAD

**Issue by bernatfp** [onflow/flow-validator#7]
### Name

Bernat Fages

### Contact Details

bernat@firstset.xyz

### Discord ID

bernatf

### What node role are you interested in operating?

- [ ] Collection
- [ ] Consensus
- [X] Verification
- [ ] Execution

### Please tell us more about why you want to run node(s) and any other relevant information.

One of our partners holds a sizable FLOW position that he wants to stake with us. We have the 135k FLOW required to bond a verification node.

### Please provide links of what you’re currently working on in the context of Flow

No plans at the moment, but we have a history of building for other ecosystems (e.g. Optimism and Eigenlayer), and would be interested in discussing delegation opportunities to fund potential contributions to Flow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishalchangrani** [comment]
The node has been added to the network.
